services:

  finrag:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8501:8501"

    env_file:
      - .env

    volumes:
      - chroma_data:/app/chroma_db
      - ./monitoring:/app/monitoring

    restart: unless-stopped

  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monitoring

    ports:
      - "8502:8502"

    volumes:
      - ./monitoring:/app/monitoring

    restart: unless-stopped

volumes:
  chroma_data: